#! /usr/bin/env perl

# command:
#   ls /lustre/beagle/$USER/Mtb/SAMN026285*/SRR*_1.fastq.gz | run-bwa-mem-on-mtb | cpar -s ~/.beagle-modules.sh -c 10 -t 8 6:00:00 test_mem_first_28

use strict;

my $usage = "Usage: echo path/SAMN02403611/SRR1172215 |$0 \n\n";

my $base = "/lustre/beagle/". $ENV{USER};
my $dest = "$base/Mtb_bwa_mem";
my $script = "$base/soot/scripts/snp.pl";
my $ref = "$base/Mtb_test/H37Rv.fa";

while (<STDIN>) {
    my ($path, $samn, $srr) = m|(\S+/)(SAMN\d+)/(SRR\d+)|;
    my $dir = "$dest/$samn";
    my $vcf = "$dir/$srr.vcf";
    next if -s $vcf;

    print "mkdir -p $dir; ";
    print "$script -t 8 -o $srr $ref $path$samn/$srr\_1.fastq.gz $path$samn/$srr\_2.fastq.gz; ";
    print "cp $srr/var.raw.vcf $vcf";
    print "\n";
 }
